version: '3.8'

services:
  db:
    image: postgres:13
    container_name: notifications_db
    environment:
      POSTGRES_DB: notifications
      POSTGRES_USER: challenge
      POSTGRES_PASSWORD: rNmRZ6DJwvxqdQP2h7yk8z
    ports:
      - "5433:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  web:
    build: .
    container_name: notifications_api
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://challenge:rNmRZ6DJwvxqdQP2h7yk8z@db/notifications
      #- SEED=True
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    networks:
      - app_network
      
  redis:
    image: "redis:alpine"
    container_name: redis_broker
    ports:
      - "6379:6379"
    networks:
      - app_network

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A src.celery.celery_app worker --loglevel=info
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data:
