"""adding usercontactmedium

Revision ID: 22ddcaa8e0ac
Revises: 8b76b4f1fcb2
Create Date: 2024-09-03 01:30:21.647703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22ddcaa8e0ac'
down_revision: Union[str, None] = '8b76b4f1fcb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
